#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export GOCACHE="${GOCACHE:-$ROOT/.cache/go-build}"
export GOTMPDIR="${GOTMPDIR:-$ROOT/.cache/go-tmp}"
export ENTERPRISE_QUOTA_COUNTER_STRESS=1
export ENTERPRISE_QUOTA_COUNTER_STRESS_MODE="${ENTERPRISE_QUOTA_COUNTER_STRESS_MODE:-all}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_WORKERS="${ENTERPRISE_QUOTA_COUNTER_STRESS_WORKERS:-32}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_OPERATIONS="${ENTERPRISE_QUOTA_COUNTER_STRESS_OPERATIONS:-200}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_ATTEMPTS="${ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_ATTEMPTS:-128}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_SUCCESSES="${ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_SUCCESSES:-64}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_RESERVE_QUOTA="${ENTERPRISE_QUOTA_COUNTER_STRESS_RESERVE_QUOTA:-10}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_REFUND_EVERY="${ENTERPRISE_QUOTA_COUNTER_STRESS_REFUND_EVERY:-5}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_ACTUAL_JITTER="${ENTERPRISE_QUOTA_COUNTER_STRESS_ACTUAL_JITTER:-3}"
export ENTERPRISE_QUOTA_COUNTER_STRESS_REDIS_BACKEND="${ENTERPRISE_QUOTA_COUNTER_STRESS_REDIS_BACKEND:-fake}"
TIMEOUT="${ENTERPRISE_QUOTA_COUNTER_STRESS_TIMEOUT:-180s}"

mkdir -p "$GOCACHE" "$GOTMPDIR"
cd "$ROOT"

echo "[enterprise-quota-counter-stress] mode=$ENTERPRISE_QUOTA_COUNTER_STRESS_MODE redis_backend=$ENTERPRISE_QUOTA_COUNTER_STRESS_REDIS_BACKEND workers=$ENTERPRISE_QUOTA_COUNTER_STRESS_WORKERS operations=$ENTERPRISE_QUOTA_COUNTER_STRESS_OPERATIONS saturation_attempts=$ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_ATTEMPTS saturation_successes=$ENTERPRISE_QUOTA_COUNTER_STRESS_SATURATION_SUCCESSES reserve_quota=$ENTERPRISE_QUOTA_COUNTER_STRESS_RESERVE_QUOTA"
go test ./service -run TestEnterpriseQuotaCounterStress -count=1 -timeout="$TIMEOUT"
